# Generated by Django 4.1.7 on 2023-04-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserRegister",),
    ]
