# Generated by Django 4.1.7 on 2023-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name="teamregister",
            name="person3",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teamregister",
            name="person4",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
