# Generated by Django 4.1.7 on 2023-04-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_teamregister_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamregister",
            name="time",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
