# Generated by Django 4.1.7 on 2023-04-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0006_teamregister_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamregister",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
