# Generated by Django 4.1.7 on 2023-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0008_teamregister_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamregister",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
